language: node_js

node_js:
  - 8

script: npm run test

before_install:
  - npm install -g npm@next

install:
  - npm ci

cache:
  directories:
    - $(npm config get prefix)/bin
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.npm
